sudo: required

services:
  - docker

before_install:
  - docker build -t padmanabh14/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -t padmanabh14/react-test npm test -- --coverage

after_success:
  - docker build -t padmanabh14/multi-client ./client
  - docker build -t padmanabh14/multi-nginx ./nginx
  - docker build -t padmanabh14/multi-server ./server
  - docker build -t padmanabh14/multi-worker ./worker

  # Log into docker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push padmanabh14/multi-client
  - docker push padmanabh14/multi-nginx
  - docker push padmanabh14/multi-server
  - docker push padmanabh14/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-041394826900
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
